- description: One Click Deployment ( with migration ) for All cluster
  executionEnabled: true
  group: Production/Bullseye/AEM/Deployment/One-Click
  id: 45d2b28d-ba1f-45cd-9c9f-fce771205074
  loglevel: INFO
  name: One Click Deployment ( with migration )
  nodeFilterEditable: false
  scheduleEnabled: false
  sequence:
    commands:
    - description: 'Step 1 : Curtain Dispatcher '
      jobref:
        group: Bullseye/Dispatcher/Deployment/Step-Wise
        name: 'Curtain Dispatcher '
        nodeStep: 'true'
    - description: 'Step 2 : Bullseyes RC Deployment'
      jobref:
        group: Bullseye/AEM/Deployment/Step-Wise
        name: Bullseyes RC Deployment
        nodeStep: 'true'
    - description: 'Step 3 : Verify Bullseye bundle versions'
      jobref:
        group: Bullseye/AEM/Deployment/Step-Wise
        name: Verify Bullseye bundle versions
        nodeStep: 'true'
    - description: 'Step 4 : Run Migration'
      jobref:
        group: Bullseye/AEM/Deployment/Step-Wise
        name: Run Migration
        nodeStep: 'true'
    - description: 'Step 5 : Verify Migration'
      jobref:
        group: Bullseye/AEM/Deployment/Step-Wise
        name: Verify Migration
        nodeStep: 'true'
    - description: 'Step 6 : Flush Dispatcher '
      jobref:
        group: Bullseye/Dispatcher/Deployment/Step-Wise
        name: 'Flush Dispatcher '
        nodeStep: 'true'
    - description: 'Step 7 :  Uncurtain Dispatcher '
      jobref:
        group: Bullseye/Dispatcher/Deployment/Step-Wise
        name: 'Uncurtain Dispatcher '
        nodeStep: 'true'
    - description: step 8
      exec: echo Ye ye `hostname`
    - description: step 9
      exec: ls -lrt
    keepgoing: false
    pluginConfig:
      WorkflowStrategy:
        node-first: null
    strategy: node-first
  uuid: 45d2b28d-ba1f-45cd-9c9f-fce771205074

