- description: ''
  executionEnabled: true
  group: Production/Bullseye/AEM/Deployment/One-Click
  id: c4f17e05-bc02-4fbf-8835-9dd03475736a
  loglevel: INFO
  name: One Click Deployment ( without migration )
  nodeFilterEditable: false
  scheduleEnabled: false
  sequence:
    commands:
    - description: 'Step 1 : Curtain Dispatcher '
      jobref:
        group: Bullseye/Dispatcher/Deployment/Step-Wise
        name: 'Curtain Dispatcher '
        nodeStep: 'true'
    - description: 'Step 2 : Bullseyes RC Deployment'
      jobref:
        group: Bullseye/AEM/Deployment/Step-Wise
        name: Bullseyes RC Deployment
        nodeStep: 'true'
    - description: 'Step 3 : Verify Bullseye bundle versions'
      jobref:
        group: Bullseye/AEM/Deployment/Step-Wise
        name: Verify Bullseye bundle versions
        nodeStep: 'true'
    - description: 'Step 4 : Flush Dispatcher'
      jobref:
        group: Bullseye/Dispatcher/Deployment/Step-Wise
        name: 'Flush Dispatcher '
        nodeStep: 'true'
    - description: 'Step 3 : Uncurtain Dispatcher '
      jobref:
        group: Bullseye/Dispatcher/Deployment/Step-Wise
        name: 'Uncurtain Dispatcher '
        nodeStep: 'true'
    keepgoing: false
    pluginConfig:
      WorkflowStrategy:
        node-first: null
    strategy: node-first
  uuid: c4f17e05-bc02-4fbf-8835-9dd03475736a

